language: csharp
solution: TestObj\TestObj.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore TestObj\TestObj.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./TestObj/TestObj/bin/Debug/TestObj.dll